SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
GRAVITY = 0.95
JUMP_STRENGTH = -16
MOVE_SPEED = 9
WIDTH = 22
HEIGHT = 32
COLOR = "#888888"
ANIMATION_FPS = 0.1
ANIMATION_RIGHT = []
ANIMATION_LEFT = []
ANIMATION_JUMP_LEFT = []
ANIMATION_JUMP_RIGHT = []
ANIMATION_JUMP = []
ANIMATION_STAY = []

